Added error handling for mongoose.connect
Adonis-Self-Improvement/ASI-API-Platform pull request #16
Opened 2022-04-11 21:41 UTC by daylimbic

Without a `.catch` statement, and on a connection error, the API would simply print nothing, rather than provide valid debug information.

2022-04-11 22:53 UTC, Vicdansanch approved these changes
Good catch , if you know what i mean

2022-04-12 05:47 UTC, swatarianess approved these changes

2022-04-12 10:53 UTC, seanjhardy requested changes
We've changed the method of connection so it needs to be mongoose.connect(process.env.DB_KEY).catch(error => console.error(error));

2022-04-14 20:57 UTC, daylimbic commented
It's been a while since I saw this, but it appears that the catch statement was completely removed after adding the env variable. Was this intentional, or due to conflicting branches? My previous statements regarding the lack of error information on a mongodb connection fail appear to still hold true.

2022-04-15 09:38 UTC, seanjhardy approved these changes

2022-04-15 09:38 UTC, merged