Error handling for the /skills POST request
Adonis-Self-Improvement/ASI-API-Platform pull request #20
Opened 2022-04-13 11:23 UTC by OmerSabic

Been a bit of a pain trying to test the POST /skills path so added some error handling to make sure the server doesn't crash every time we have a bad input.

2022-04-13 12:10 UTC, OmerSabic commented
Sorry for the messy commits, a lot of things were changed

2022-04-14 21:57 UTC, swatarianess approved these changes

2022-04-15 09:18 UTC, vinicius404 approved these changes

2022-04-15 09:21 UTC, seanjhardy requested changes
Change validation from "iconName: skill.iconName" to "title : skill.title"
Because the composite key is Title and level, not icon and level

2022-04-15 09:41 UTC, seanjhardy approved these changes

2022-04-15 09:42 UTC, merged